# Встроенные исключения


Мы собираемся показать Вам краткий список самых полезных исключений. Может показаться странным, называть "полезной" вещь или явление, которое является явным признаком неудачи или проблемы. Как Вы знаете, если что-то может пойти не так, оно пойдет не так.

Исключения являются такими же рутинными и нормальными вещами, как и любой другой аспект жизни программиста.


Для каждого исключения мы покажем:

*   его имя;
*   его местоположение в дереве исключений;
*   краткое описание;
*   краткий фрагмент кода, показывающий обстоятельства, при которых может возникнуть исключение.


Есть много других исключений для изучения - у нас просто нет времени, чтобы просмотреть их все в этом курсе.


## `ArithmeticError`

**Расположение:** `BaseException ← Exception ← ArithmeticError`

**Описание:** абстрактное исключение, включающее в себя все исключения, вызванные арифметическими операциями, такими как деление на ноль или недопустимый тип аргумента.


## `AssertionError`

**Расположение:** `BaseException ← Exception ← AssertionError`

**Описание:** конкретное исключение, вызываемое инструкцией `assert`, когда ее аргумент оценивается как `False`, `None`, `0` или пустой строкой.

**Пример кода:**

```python
from math import tan, radians
angle = int(input('Введите интегральный угол в градусах: '))

# мы должны быть уверены, что angle != 90 + k * 180
assert angle % 180 != 90
print(tan(radians(angle)))

```


## `BaseException`

**Расположение:** `BaseException`

**Описание:** самое общее (абстрактное) из всех исключений Python - все остальные исключения включены в него; Можно сказать, что следующие две ветви except эквивалентны: `except:` и `except BaseException:`.


## `IndexError`

**Расположение:** `BaseException ← Exception ← LookupError ← IndexError`

**Описание:** конкретное исключение, возникающее при попытке доступа к элементу несуществующей последовательности (например, элементу списка).

**Пример кода:**

```python
# код показывает экстравагантный способ
# выхода из цикла

list = [1, 2, 3, 4, 5]
ix = 0
doit = True

while doit:
    try:
        print(list[ix])
        ix += 1
    except IndexError:
        doit = False

print('Готово')

```


## `KeyboardInterrupt`

**Расположение:** `BaseException ← KeyboardInterrupt`

**Описание:** конкретное исключение, возникающее, когда пользователь использует сочетание клавиш, предназначенное для прекращения выполнения программы (_Ctrl-C_ в большинстве ОС); если обработка этого исключения не приводит к завершению программы, программа продолжает выполнение. Примечание: это исключение не является производным от класса `Exception`. Запустите программу в IDLE.

**Пример кода:**

```python
# этот код не может быть завершен
# нажатием Ctrl-C

from time import sleep
seconds = 0
while True:
    try:
        print(seconds)
        seconds += 1
        sleep(1)
    except KeyboardInterrupt:
        print("Не делайте этого!")

```

## `LookupError`


**Расположение:** `BaseException ← Exception ← LookupError`

**Описание:** абстрактное исключение, включающее все исключения, вызванные ошибками, возникшими из-за недопустимых ссылок на разные наборы данных (списки, словари, кортежи и т.д.).


## `MemoryError`

**Расположение:** `BaseException ← Exception ← MemoryError`

**Описание:** конкретное исключение, возникающее, когда операция не может быть завершена из-за недостатка свободной памяти.

**Пример кода:**

```python
# этот код вызывает исключение MemoryError
# предупреждение: выполнение этого кода может быть критичным
# для вашей ОС
# не используйте его в производственных средах!

string = 'x'
try:
    while True:
        string = string + string
        print(len(string))
except MemoryError:
    print('Это не смешно!')

```


## `OverflowError`

**Расположение:** `BaseException ← Exception ← ArithmeticError ← OverflowError`

**Описание:** конкретное исключение, возникающее, когда операция выдает значение такого размера, что его невозможно разместить в переменной.

**Пример кода:**

```python
# код печатает последовательность
# значений exp(k), k = 1, 2, 4, 8, 16, ...

from math import exp
ex = 1
try:
    while True:
        print(exp(ex))
        ex *= 2
except OverflowError:
    print('Число слишком большое.')

```


## `ImportError`

**Расположение:** `BaseException ← Exception ← StandardError ← ImportError`

**Описание:** конкретное исключение, возникающее при сбое операции импорта.

**Пример кода:**

```python
# один из этих импортов потерпит неудачу - какой?

try:
    import math
    import time
    import abracadabra

except:
    print('Один из ваших импортов не удался.')

```


## `KeyError`

**Расположение:** `BaseException ← Exception ← LookupError ← KeyError`

**Описание:** конкретное исключение, возникающее при попытке доступа к несуществующему элементу набора данных (например, к элементу словаря)


**Пример кода:**

```python
# как злоупотреблять словарем
# и как с этим справиться

dict = { 'a' : 'b', 'b' : 'c', 'c' : 'd' }
ch = 'a'
try:
    while True:
        ch = dict[ch]
        print(ch)
except KeyError:
    print('Нет такого ключа:', ch)

```

На данный момент мы закончим рассмотрение возможных исключений, но мы еще вернемся к ним, когда обсудим объектно-ориентированное программирование на Python. Вы можете использовать их для защиты своего кода от несчастных случаев, но Вы также должны научиться погружаться в них, исследуя информацию, которую они несут.

Исключения на самом деле являются объектами - однако мы ничего не можем Вам сказать об этом аспекте, пока не представим Вам классы, объекты и прочее.

В настоящее время, если Вы хотите больше узнать об исключениях самостоятельно, обратитесь к Стандартной библиотеке Python по адресу [https://docs.python.org/3.6/library/exceptions.html](https://docs.python.org/3.6/library/exceptions.html).


# Основные тезисы

1. Некоторые абстрактные встроенные исключения Python:

   *   `ArithmeticError`,
   *   `BaseException`,
   *   `LookupError`.


2. Некоторые конкретные встроенные исключения Python:

   *   `AssertionError`,
   *   `ImportError`,
   *   `IndexError`,
   *   `KeyboardInterrupt`,
   *   `KeyError`,
   *   `MemoryError`,
   *   `OverflowError`.

---  

**Упражнение 1**

Какое исключение Вы будете использовать, чтобы защитить свой код от прерывания с помощью клавиатуры?

<details><summary>Проверка</summary>

`KeyboardInterrupt`

</details>

---

**Упражнение 2**

Как называется наиболее общее исключение Python?

<details><summary>Проверка</summary>

`BaseException`

</details>

---

**Упражнение 3**

Какие исключения будут вызваны следующим неудачным вычислением?

```python
huge_value = 1E250 ** 2
```
  
<details><summary>Проверка</summary>

`OverflowError`

</details>



# Поздравляем! Вы завершили _Основы Python 2: Модуль 2_.

Отличная работа! Вы достигли конца Модуля 2 и завершили важный этап в своем образовании по программированию на Python. Вот краткое изложение задач, которые Вы рассмотрели и с которыми ознакомились в Модуле 2:

*   символы, строки и стандарты кодирования;
*   природа строк в Python; строки и списки - сходства и различия;
*   методы списков и строк;
*   обработка ошибок в Python;
*   управление потоком ошибок с помощью _try_ и _except_;
*   иерархия исключений; обзор наиболее полезных исключений.


Теперь Вы готовы пройти тест по модулю и попытаться выполнить последнее задание: экзамен к Модулю 2, который поможет Вам оценить то, чему Вы научились на данный момент.


![Module completion – congratulations](./assets/29ed2aa31a1a26221e4eac3b69d973a33cbf562e.png)



